matrix:
  include:
    - language: generic
      cache: yarn
      before_install:
        - nvm install && nvm use && nvm alias default current
        - curl -o- -L https://yarnpkg.com/install.sh | bash
        - export PATH="$HOME/.yarn/bin:$PATH"
      install: yarn install
      script: yarn test

    - language: python
      before_install:
        - pip install pre-commit
      script: pre-commit run --all-files
      cache:
        directories:
          - $HOME/.cache/pre-commit

branches:
  only:
    - master
